### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by MichelGerding** [primer/components#894]
**Describe the bug**
When trying to install the module i get the error
`npm ERR! Unexpected end of JSON input while parsing near '..."fs-extra":"7.0.0","g'`

**To Reproduce**
1. Create new node project using `npm init -y`
2. run the installation command `npm install --save @primer/components`

**Expected behavior**
The expected behavior is that it gets installed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node: 11..13.0
 - Npm: 6.14.8

 - Version: 20.3.0

**Additional context**
The complete error log is 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\miche\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@primer/components' ]
2 info using npm@6.14.8
3 info using node@v11.13.0
4 verbose npm-session 2fb4e79bf6697e14
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@primer%2fcomponents 1031ms (from cache)
8 silly fetchPackageMetaData error for @primer/components@latest Unexpected end of JSON input while parsing near '..."fs-extra":"7.0.0","g'
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 1075ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."fs-extra":"7.0.0","g'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (C:\Users\miche\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (C:\Users\miche\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:86:5)
12 verbose cwd C:\Users\miche\test
13 verbose Windows_NT 10.0.19041
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\miche\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@primer/components"
15 verbose node v11.13.0
16 verbose npm  v6.14.8
17 error Unexpected end of JSON input while parsing near '..."fs-extra":"7.0.0","g'
18 verbose exit [ 1, true ]
```
and the terminal output is 
```
npm ERR! Unexpected end of JSON input while parsing near '..."fs-extra":"7.0.0","g'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\miche\AppData\Roaming\npm-cache\_logs\2020-11-01T08_32_47_301Z-debug.log
```

**Comment by colebemis** [comment]
@MichelGerding Sorry for the delay. Is this still an issue?

**Comment by MichelGerding** [comment]
this is no longer an issue. it installs just fine even with the version I was using at the time
