### ISSUE TITLE
SelectMenu.Modal: prop type `width` is invalid; it must be a function

### ISSUE THREAD

**Issue by semantic-project** [primer/components#906]
Warning: Failed prop type: SelectMenu.Modal: prop type `width` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.This often happens because of typos such as `PropTypes.function` instead of `PropTypes.func`.
    at SelectMenu.Modal (http://localhost:3000/static/js/0.chunk.js:4507:23)
    at MyMenu
    at div
    at Box (http://localhost:3000/static/js/0.chunk.js:64585:6)
    at div
    at Box (http://localhost:3000/static/js/0.chunk.js:64585:6)
    at div
    at Box (http://localhost:3000/static/js/0.chunk.js:64585:6)
    at div
    at Base (http://localhost:3000/static/js/0.chunk.js:1238:21)
    at BaseStyles (http://localhost:3000/static/js/0.chunk.js:64585:6)

**Comment by emplums** [comment]
Thanks for the heads up! I've been meaning to fix this, will get it in in the next release
